version: "3.5"

services:
  postgres-tolanguage:
    container_name: postgres-tolanguage
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./.docker-volumes/postgres:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      tolanguage-net:
        ipv4_address: 172.28.1.1

  liquibase-tolanguage:
    container_name: liquibase-tolanguage
    image: liquibase/liquibase:${LIQUIBASE_VERSION}
#    restart: on-failure
    command: --defaultsFile=liquibase.properties update
    depends_on:
      - postgres-tolanguage
    volumes:
      - ./db/:/liquibase/changelog/
      - ./db/:/liquibase/classpath/
      - ./db/liquibase.properties:/liquibase/liquibase.properties
    networks:
      tolanguage-net:
        ipv4_address: 172.28.1.2

networks:
  tolanguage-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16