debug: ${SPRING_DEBUG:false}
server:
  port: ${APP_PORT:9000}
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: 5000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 2
      max-lifetime: 120000
      idle-timeout: 300000
    url: ${POSTGRES_URL}?currentSchema=${POSTGRES_SCHEMA:tolanguage}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: tolanguage

cache:
  user-maximum-size: 100000
  user-expired-time-hours: 4

app:
  url: ${APP_URL}
  api-path: ${API_PATH:/}
  salt: ${HASH_SALT}
  jwt-signing-key: ${JWT_SIGNING_KEY}
  token-ttl: ${TOKEN_TTL:4}